name: Publish stage2

on:
  push:
    tags:
      - stage2/v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: |
            8
            16
            17

      - name: Build
        run: ./gradlew :stage2:{launchwrapper,fabric,modlauncher{8,9}}:build --stacktrace

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: stage2/*/build/libs/*.jar

      # TODO: publish to Essential infra on staging channel once there is an API to do that
